[[redirects]]
  from = "https://ayyub29.id/eval"
  to = "https://forms.gle/oBhPcm6j1T8LY89B7"
  status = 301
  force = true

[[redirects]]
  from = "https://ayyub29.id/meet"
  to = "https://meet.google.com/uhj-vsyw-iih"
  status = 301
  force = true

[[redirects]]
  from = "https://ayyub29.id/mau-bayar-yt"
  to = "https://forms.gle/DayjDoEdEW58HmvYA"
  status = 301
  force = true
  
[[redirects]]
  from = "https://ayyub29.id/sudah-bayar-yt"
  to = "https://docs.google.com/spreadsheets/d/1_wACR2bRZa4KcJMSTd6RLJAWfI9woUC4KIkP8GBZ_-E/edit?usp=sharing"
  status = 301
  force = true
  
