[[redirects]]
  from = "https://ayyub29.id/eval"
  to = "https://forms.gle/oBhPcm6j1T8LY89B7"
  status = 301
  force = true

[[redirects]]
  from = "https://ayyub29.id/meet"
  to = "https://meet.google.com/uhj-vsyw-iih"
  status = 301
  force = true

[[redirects]]
  from = "https://ayyub29.id/bayar-yt"
  to = "https://forms.gle/DayjDoEdEW58HmvYA"
  status = 301
  force = true
